### PR TITLE
MRG: Internal consistency

### PR DESCRIPTION
**Pull request by kellieotto**

### CODE REVIEW

**Comment by jarrodmillman** [comment]
This looks good to me.  Are you done or still working?  If you want to merge this, go ahead and I will rebase my pull request.

**Comment by kellieotto** [comment]
I'm going to do one more thing with two_sample -- add an argument to optionally return the simulated null distribution.  I hope to be done this evening.

**Comment by jarrodmillman** [comment]
Cool.  I will keep working and rebase off you once you merge this.

**Comment by jarrodmillman** [comment]
I prepended `WIP` to the title to indicate that work is still in progress.  Once you are done change it to MRG and merge or leave it and I will merge it when I see that you have updated the status to indicate you are ready for it to be merged.

**Pull request merged**
